INSERT INTO `events_region` (id, name) VALUES (1, 'Alsace');
INSERT INTO `events_region` (id, name) VALUES (2, 'Aquitaine');
INSERT INTO `events_region` (id, name) VALUES (3, 'Auvergne');
INSERT INTO `events_region` (id, name) VALUES (4, 'Bourgogne');
INSERT INTO `events_region` (id, name) VALUES (5, 'Bretagne');
INSERT INTO `events_region` (id, name) VALUES (6, 'Centre');
INSERT INTO `events_region` (id, name) VALUES (7, 'Champagne-Ardenne');
INSERT INTO `events_region` (id, name) VALUES (8, 'Corse');
INSERT INTO `events_region` (id, name) VALUES (9, 'Franche-Comté');
INSERT INTO `events_region` (id, name) VALUES (10, 'Ile-de-France');
INSERT INTO `events_region` (id, name) VALUES (11, 'Languedoc-Roussillon');
INSERT INTO `events_region` (id, name) VALUES (12, 'Limousin');
INSERT INTO `events_region` (id, name) VALUES (13, 'Lorraine');
INSERT INTO `events_region` (id, name) VALUES (14, 'Midi-Pyrénées');
INSERT INTO `events_region` (id, name) VALUES (15, 'Nord-Pas-de-Calais');
INSERT INTO `events_region` (id, name) VALUES (16, 'Basse-Normandie');
INSERT INTO `events_region` (id, name) VALUES (17, 'Haute-Normandie');
INSERT INTO `events_region` (id, name) VALUES (18, 'Pays de la Loire');
INSERT INTO `events_region` (id, name) VALUES (19, 'Picardie');
INSERT INTO `events_region` (id, name) VALUES (20, 'Poitou-Charentes');
INSERT INTO `events_region` (id, name) VALUES (21, 'Provence-Alpes-Côte d''Azur');
INSERT INTO `events_region` (id, name) VALUES (22, 'Rhône-Alpes');
INSERT INTO `events_region` (id, name) VALUES (23, 'Belgique');
INSERT INTO `events_region` (id, name) VALUES (24, 'Autre province, état, pays');
